FROM node:18

WORKDIR /app

# Копируем package.json отдельно для кэширования
COPY package*.json ./
RUN npm install

# Копируем исходный код
COPY . .

# Запускаем в режиме разработки
CMD ["npm", "start"]